# Render.com deployment configuration for backend
version: "1"

services:
  # Backend API Service
  - type: web
    name: sdh-ai-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false # Set manually in Render dashboard
      - key: DATABASE_PATH
        value: ./database.sqlite

# Database persistence (for paid plans)
databases:
  - name: sdh-ai-database
    databaseName: sdh_ai_assistant
    user: sdh_ai_user